r"""Regenerate the Curry twin of tool 7bis (automatic epoch rejection) from its EDF source.

Tool 7bis is FORMAT-AGNOSTIC: it reads only the tool-6 `{file_id}_all-epo.fif` and
`{file_id}_epoch_channel_rejection.tsv`, which the Curry tool 6 writes in the identical MNE/TSV format
(same `derivatives/` + `reports_preprocessing/` layout). There is no EDF-specific signal loading to swap
(unlike tools 5/6, whose generators replace `read_raw_edf` / suffix-dedup blocks), so the Curry twin is a
**verbatim copy** of the EDF notebook with only the title retitled.

Re-run this after editing `tools/7bis_reject_automatically_voila.ipynb`:
    & "$env:LOCALAPPDATA\miniforge3\envs\inspect_edf\python.exe" tools_curry/_make_tool7bis_curry.py
"""
import ast
import json
from pathlib import Path

SRC = Path(__file__).resolve().parent.parent / 'tools' / '7bis_reject_automatically_voila.ipynb'
DST = Path(__file__).resolve().parent / '7bis_reject_automatically_curry_voila.ipynb'

nb = json.loads(SRC.read_text(encoding='utf-8'))

# --- retitle the first markdown cell (the ONLY change vs the EDF twin) ---
title_cell = nb['cells'][0]
src = ''.join(title_cell['source'])
old_h1 = '# Tool 7bis — Automatic epoch rejection (channel-first, then epoch)'
new_h1 = ('# Tool 7bis — Automatic epoch rejection — Curry twin (channel-first, then epoch)\n\n'
          '*Curry twin: functionally identical to the EDF tool 7bis. 7bis reads only tool-6 '
          '`*_all-epo.fif` + `*_epoch_channel_rejection.tsv`, which the Curry tool 6 writes in the same '
          'MNE/TSV format, so no code differs. Generated by `tools_curry/_make_tool7bis_curry.py` — '
          'do not hand-edit; edit the EDF notebook and re-run the generator.*')
assert src.count(old_h1) == 1, 'title anchor not found — did the EDF twin H1 change?'
src = src.replace(old_h1, new_h1)
title_cell['source'] = src.splitlines(keepends=True)

# --- syntax gate: every code cell must still parse ---
for c in nb['cells']:
    if c['cell_type'] == 'code':
        ast.parse(''.join(c['source']))

DST.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + '\n', encoding='utf-8')
print(f'Wrote {DST}')
